"""
    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will be:

                     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    Find the sum of all the even-valued terms in the sequence which do not
    exceed four million.

    Answer: 4613732

"""

fib = []
total = 0

fib.append(1)
fib.append(2)
to_add = 0
x = 2

while to_add < 4000000:
    two_less = fib[x - 2]
    one_less = fib[x - 1]
    to_add = one_less + two_less
    if to_add > 4000000:
        break
    else:
        fib.append(to_add)
    x += 1

for x in range(0, fib.__len__()):
    if fib[x] % 2 == 0:
        total += fib[x]

print total
